// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type User struct {
	GithubID           string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Wallet             int64
	AmountBetLifetime  int64
	AmountWonLifetime  int64
	AmountLostLifetime int64
	HandsPlayed        int64
	HandsWon           int64
	HandsLost          int64
	GithubStarred      bool
	LastLogin          time.Time
	LoginStreak        int64
	Blackjacks         int64
}
