// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(github_id, created_at, updated_at, last_login)
VALUES (?, ?, ?, ?)
RETURNING github_id, created_at, updated_at, wallet, amount_bet_lifetime, amount_won_lifetime, amount_lost_lifetime, hands_played, hands_won, hands_lost, github_starred, last_login, login_streak, blackjacks
`

type CreateUserParams struct {
	GithubID  string
	CreatedAt time.Time
	UpdatedAt time.Time
	LastLogin time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.GithubID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastLogin,
	)
	var i User
	err := row.Scan(
		&i.GithubID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Wallet,
		&i.AmountBetLifetime,
		&i.AmountWonLifetime,
		&i.AmountLostLifetime,
		&i.HandsPlayed,
		&i.HandsWon,
		&i.HandsLost,
		&i.GithubStarred,
		&i.LastLogin,
		&i.LoginStreak,
		&i.Blackjacks,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select github_id, created_at, updated_at, wallet, amount_bet_lifetime, amount_won_lifetime, amount_lost_lifetime, hands_played, hands_won, hands_lost, github_starred, last_login, login_streak, blackjacks
from users
where github_id = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, githubID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, githubID)
	var i User
	err := row.Scan(
		&i.GithubID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Wallet,
		&i.AmountBetLifetime,
		&i.AmountWonLifetime,
		&i.AmountLostLifetime,
		&i.HandsPlayed,
		&i.HandsWon,
		&i.HandsLost,
		&i.GithubStarred,
		&i.LastLogin,
		&i.LoginStreak,
		&i.Blackjacks,
	)
	return i, err
}

const updateGithubStarred = `-- name: UpdateGithubStarred :one
;
UPDATE users 
SET updated_at = CURRENT_TIMESTAMP,
github_starred = ?
WHERE github_id = ?
RETURNING github_id, created_at, updated_at, wallet, amount_bet_lifetime, amount_won_lifetime, amount_lost_lifetime, hands_played, hands_won, hands_lost, github_starred, last_login, login_streak, blackjacks
`

type UpdateGithubStarredParams struct {
	GithubStarred bool
	GithubID      string
}

func (q *Queries) UpdateGithubStarred(ctx context.Context, arg UpdateGithubStarredParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateGithubStarred, arg.GithubStarred, arg.GithubID)
	var i User
	err := row.Scan(
		&i.GithubID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Wallet,
		&i.AmountBetLifetime,
		&i.AmountWonLifetime,
		&i.AmountLostLifetime,
		&i.HandsPlayed,
		&i.HandsWon,
		&i.HandsLost,
		&i.GithubStarred,
		&i.LastLogin,
		&i.LoginStreak,
		&i.Blackjacks,
	)
	return i, err
}

const updateLoginStreak = `-- name: UpdateLoginStreak :one
;

UPDATE users
SET updated_at = CURRENT_TIMESTAMP,
last_login = CURRENT_TIMESTAMP,
login_streak = ?
WHERE github_id = ?
RETURNING github_id, created_at, updated_at, wallet, amount_bet_lifetime, amount_won_lifetime, amount_lost_lifetime, hands_played, hands_won, hands_lost, github_starred, last_login, login_streak, blackjacks
`

type UpdateLoginStreakParams struct {
	LoginStreak int64
	GithubID    string
}

func (q *Queries) UpdateLoginStreak(ctx context.Context, arg UpdateLoginStreakParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateLoginStreak, arg.LoginStreak, arg.GithubID)
	var i User
	err := row.Scan(
		&i.GithubID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Wallet,
		&i.AmountBetLifetime,
		&i.AmountWonLifetime,
		&i.AmountLostLifetime,
		&i.HandsPlayed,
		&i.HandsWon,
		&i.HandsLost,
		&i.GithubStarred,
		&i.LastLogin,
		&i.LoginStreak,
		&i.Blackjacks,
	)
	return i, err
}

const updateUserAddIncome = `-- name: UpdateUserAddIncome :one
;

UPDATE users
SET updated_at = CURRENT_TIMESTAMP,
last_login = CURRENT_TIMESTAMP,
wallet = wallet + ?
WHERE github_id = ?
RETURNING github_id, created_at, updated_at, wallet, amount_bet_lifetime, amount_won_lifetime, amount_lost_lifetime, hands_played, hands_won, hands_lost, github_starred, last_login, login_streak, blackjacks
`

type UpdateUserAddIncomeParams struct {
	Wallet   int64
	GithubID string
}

func (q *Queries) UpdateUserAddIncome(ctx context.Context, arg UpdateUserAddIncomeParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserAddIncome, arg.Wallet, arg.GithubID)
	var i User
	err := row.Scan(
		&i.GithubID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Wallet,
		&i.AmountBetLifetime,
		&i.AmountWonLifetime,
		&i.AmountLostLifetime,
		&i.HandsPlayed,
		&i.HandsWon,
		&i.HandsLost,
		&i.GithubStarred,
		&i.LastLogin,
		&i.LoginStreak,
		&i.Blackjacks,
	)
	return i, err
}

const updateUserStats = `-- name: UpdateUserStats :one
;

UPDATE users
SET updated_at = CURRENT_TIMESTAMP,
wallet = ?,
amount_bet_lifetime = amount_bet_lifetime + ?,
amount_won_lifetime = amount_won_lifetime + ?,
amount_lost_lifetime = amount_lost_lifetime + ?,
hands_played = hands_played + 1,
hands_won = hands_won + ?,
hands_lost = hands_lost + ?,
blackjacks = blackjacks + ?
WHERE github_id = ?
RETURNING github_id, created_at, updated_at, wallet, amount_bet_lifetime, amount_won_lifetime, amount_lost_lifetime, hands_played, hands_won, hands_lost, github_starred, last_login, login_streak, blackjacks
`

type UpdateUserStatsParams struct {
	Wallet             int64
	AmountBetLifetime  int64
	AmountWonLifetime  int64
	AmountLostLifetime int64
	HandsWon           int64
	HandsLost          int64
	Blackjacks         int64
	GithubID           string
}

func (q *Queries) UpdateUserStats(ctx context.Context, arg UpdateUserStatsParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserStats,
		arg.Wallet,
		arg.AmountBetLifetime,
		arg.AmountWonLifetime,
		arg.AmountLostLifetime,
		arg.HandsWon,
		arg.HandsLost,
		arg.Blackjacks,
		arg.GithubID,
	)
	var i User
	err := row.Scan(
		&i.GithubID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Wallet,
		&i.AmountBetLifetime,
		&i.AmountWonLifetime,
		&i.AmountLostLifetime,
		&i.HandsPlayed,
		&i.HandsWon,
		&i.HandsLost,
		&i.GithubStarred,
		&i.LastLogin,
		&i.LoginStreak,
		&i.Blackjacks,
	)
	return i, err
}
